# Generated by Django 5.0 on 2024-01-08 03:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('sender', models.EmailField(max_length=75)),
                ('app_password', models.CharField(max_length=16, validators=[django.core.validators.MinLengthValidator(16)])),
                ('body', models.TextField()),
            ],
        ),
    ]
